# Generated by Django 3.2 on 2021-06-21 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BOLETA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_boleta', models.DateTimeField(auto_now=True)),
                ('total_a_pagar', models.IntegerField(default=None)),
                ('estado', models.IntegerField(default=None)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CATEGORIA_PROVEEDOR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CLIENTE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run', models.CharField(default=None, max_length=10)),
                ('nombre', models.CharField(default=None, max_length=100)),
                ('telefono', models.CharField(default=None, max_length=12)),
                ('correo', models.CharField(default=None, max_length=128)),
                ('direccion', models.CharField(default=None, max_length=150)),
                ('estado', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='FAMILIA_PRODUCTO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PROVEEDOR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(default=None, max_length=100)),
                ('correo', models.CharField(default=None, max_length=100)),
                ('telefono', models.CharField(default=None, max_length=12)),
                ('direccion', models.CharField(default=None, max_length=150)),
                ('estado', models.IntegerField(default=None)),
                ('categoria_proveedor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='src.categoria_proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='TIPO_PRODUCTO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(default=None, max_length=150)),
                ('proveedor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='src.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='SEGUIMIENTO_PAGINA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateTimeField(auto_now=True)),
                ('pagina_visitada', models.CharField(default=None, max_length=50)),
                ('usuario', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PRODUCTO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default=None, max_length=100)),
                ('precio', models.IntegerField(default=None)),
                ('descripcion', models.CharField(blank=True, default=None, max_length=200)),
                ('precio_compra', models.IntegerField(default=None)),
                ('stock', models.IntegerField(default=None)),
                ('stock_critico', models.IntegerField(default=None)),
                ('estado', models.IntegerField(default=None)),
                ('fecha_vencimiento', models.DateTimeField(blank=True)),
                ('codigo_barra', models.CharField(default=None, max_length=18)),
                ('familia_producto', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='src.familia_producto')),
            ],
        ),
        migrations.CreateModel(
            name='PAGO_FIADO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.IntegerField(default=None)),
                ('monto', models.IntegerField(default=None)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('fecha_final', models.DateTimeField()),
                ('cliente', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='src.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='ORDEN_PEDIDO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_recepcion', models.IntegerField(default=None)),
                ('fecha_pedido', models.DateField(auto_now=True)),
                ('fecha_llegada', models.DateField(blank=True, null=True)),
                ('fecha_recepcion', models.DateField(blank=True, null=True)),
                ('hora_recepcion', models.TimeField(blank=True, null=True)),
                ('proveedor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='src.proveedor')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='familia_producto',
            name='tipo_producto',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='src.tipo_producto'),
        ),
        migrations.CreateModel(
            name='DETALLE_ORDEN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=None)),
                ('orden_pedido', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='src.orden_pedido')),
                ('producto', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='src.producto')),
            ],
        ),
        migrations.CreateModel(
            name='DETALLE_FIADO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_abonado', models.IntegerField(default=None)),
                ('fecha_abono', models.DateTimeField(auto_now=True)),
                ('pago_fiado', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='src.pago_fiado')),
            ],
        ),
        migrations.CreateModel(
            name='DETALLE_BOLETA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=None)),
                ('monto_a_pagar', models.IntegerField(default=None)),
                ('boleta', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='src.boleta')),
                ('producto', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='src.producto')),
            ],
        ),
        migrations.AddField(
            model_name='boleta',
            name='cliente',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='src.cliente'),
        ),
        migrations.AddField(
            model_name='boleta',
            name='usuario',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
