# Generated by Django 3.2 on 2021-06-04 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden_pedido',
            name='fecha_llegada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orden_pedido',
            name='fecha_recepcion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orden_pedido',
            name='hora_recepcion',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
