# Generated by Django 3.2.1 on 2021-05-09 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden_pedido',
            name='fecha_llegada',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='orden_pedido',
            name='fecha_pedido',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='orden_pedido',
            name='fecha_recepcion',
            field=models.DateField(blank=True),
        ),
    ]
