# Generated by Django 3.2.1 on 2021-05-09 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_auto_20210509_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden_pedido',
            name='hora_recepcion',
            field=models.TimeField(blank=True),
        ),
    ]
