# Generated by Django 3.2 on 2021-05-22 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_alter_orden_pedido_hora_recepcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo_barra',
            field=models.BigIntegerField(default=None),
        ),
    ]
