# Generated by Django 3.2 on 2021-05-27 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_alter_producto_codigo_barra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago_fiado',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
