# Generated by Django 3.2 on 2021-05-30 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0006_alter_pago_fiado_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='cliente',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='src.cliente'),
        ),
    ]
