# Generated by Django 3.2 on 2021-05-31 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0007_alter_boleta_cliente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boleta',
            options={'ordering': ['id']},
        ),
        migrations.RenameField(
            model_name='seguimiento_pagina',
            old_name='fecha_abono',
            new_name='fecha_ingreso',
        ),
        migrations.RemoveField(
            model_name='seguimiento_pagina',
            name='razon_social',
        ),
    ]
